// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	internal "github.com/eddyvy/tfg-go-cli/internal"
	mock "github.com/stretchr/testify/mock"
)

// CliNewI is an autogenerated mock type for the CliNewI type
type CliNewI struct {
	mock.Mock
}

// ConfigureDatabase provides a mock function with given fields: conf
func (_m *CliNewI) ConfigureDatabase(conf *internal.GlobalConfig) error {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureDatabase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.GlobalConfig) error); ok {
		r0 = rf(conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateNewProject provides a mock function with given fields: conf
func (_m *CliNewI) CreateNewProject(conf *internal.GlobalConfig) error {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.GlobalConfig) error); ok {
		r0 = rf(conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FormatProject provides a mock function with given fields: conf
func (_m *CliNewI) FormatProject(conf *internal.GlobalConfig) error {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for FormatProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.GlobalConfig) error); ok {
		r0 = rf(conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GoModDownloadProject provides a mock function with given fields: conf
func (_m *CliNewI) GoModDownloadProject(conf *internal.GlobalConfig) error {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for GoModDownloadProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.GlobalConfig) error); ok {
		r0 = rf(conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadFlagsConfig provides a mock function with given fields: projectName
func (_m *CliNewI) ReadFlagsConfig(projectName string) (*internal.GlobalConfig, error) {
	ret := _m.Called(projectName)

	if len(ret) == 0 {
		panic("no return value specified for ReadFlagsConfig")
	}

	var r0 *internal.GlobalConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*internal.GlobalConfig, error)); ok {
		return rf(projectName)
	}
	if rf, ok := ret.Get(0).(func(string) *internal.GlobalConfig); ok {
		r0 = rf(projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.GlobalConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TidyProject provides a mock function with given fields: conf
func (_m *CliNewI) TidyProject(conf *internal.GlobalConfig) error {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for TidyProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.GlobalConfig) error); ok {
		r0 = rf(conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCliNewI creates a new instance of CliNewI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCliNewI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CliNewI {
	mock := &CliNewI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
